-- =========================================================================
-- Overarc SmartBot SaaS - Supabase PostgreSQL Database Schema
-- =========================================================================

-- 1. Enable UUID Extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. Businesses Table (Multi-tenant settings)
CREATE TABLE IF NOT EXISTS businesses (
  id VARCHAR(80) PRIMARY KEY, -- Maps to botId (e.g. 'clinic', 'realestate', 'restaurant')
  name TEXT NOT NULL,
  industry TEXT, -- e.g. 'clinic' / 'realestate' / 'restaurant'
  emoji TEXT DEFAULT '🏥',
  color VARCHAR(10) DEFAULT '#E8471C',
  dark_color VARCHAR(10) DEFAULT '#C2410C',
  whatsapp TEXT,
  email TEXT,                 -- Lead notification email for business owner
  password_hash TEXT,         -- bcrypt hash for per-client JWT login
  status VARCHAR(20) DEFAULT 'active', -- 'active' | 'trial' | 'suspended'
  greeting TEXT,
  system_prompt TEXT NOT NULL,
  faqs JSONB DEFAULT '[]'::jsonb,
  services JSONB DEFAULT '[]'::jsonb,
  working_hours TEXT DEFAULT '9 AM - 6 PM',
  location TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 3. Leads Table (Captured customers profiling)
CREATE TABLE IF NOT EXISTS leads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bot VARCHAR(80) REFERENCES businesses(id) ON DELETE CASCADE,
  business TEXT,
  name TEXT NOT NULL,
  phone TEXT NOT NULL,
  topic TEXT DEFAULT 'General Inquiry',
  timestamp TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 4. Appointments Table (E-commerce / Reservations bookings)
CREATE TABLE IF NOT EXISTS appointments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bot VARCHAR(80) REFERENCES businesses(id) ON DELETE CASCADE,
  customer_name TEXT NOT NULL,
  customer_phone TEXT NOT NULL,
  service TEXT NOT NULL,
  preferred_date TEXT NOT NULL,
  preferred_time TEXT NOT NULL,
  status VARCHAR(20) DEFAULT 'pending',
  timestamp TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 5. Chat Logs Table (Inference historical threads)
CREATE TABLE IF NOT EXISTS chat_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bot VARCHAR(80) REFERENCES businesses(id) ON DELETE CASCADE,
  session_id TEXT,
  role VARCHAR(20), -- 'user' or 'assistant'
  content TEXT NOT NULL,
  timestamp TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 6. Insert Default Multi-Tenant Profiles for Instant Dev Running
INSERT INTO businesses (id, name, industry, emoji, color, dark_color, whatsapp, greeting, system_prompt, faqs, services, working_hours, location)
VALUES 
  (
    'clinic', 
    'City Dental Clinic', 
    'clinic', 
    '🏥', 
    '#22C55E', 
    '#15803D', 
    '+923249116764', 
    'Hello! 👋 Welcome to City Dental Clinic. I am your AI assistant. How can I help you today?', 
    'You are a helpful AI assistant for City Dental Clinic. Location: Mingora, Swat. Hours: 9 AM - 8 PM. FAQs:\n{FAQS_LIST}\nServices:\n{SERVICES_LIST}. Keep responses short (max 2 sentences). Ask for name and phone number to confirm bookings.',
    '[{"q": "What are your hours?", "a": "We are open 9 AM to 8 PM Monday through Saturday."}, {"q": "Where is the clinic?", "a": "We are located at Main G.T. Road, Mingora, Swat."}]'::jsonb,
    '[{"name": "Teeth Whitening", "price": "PKR 5,000"}, {"name": "Dental Scaling", "price": "PKR 2,500"}, {"name": "Root Canal Treatment", "price": "PKR 12,000"}]'::jsonb,
    '9 AM - 8 PM', 
    'Mingora, Swat'
  ),
  (
    'realestate', 
    'Al-Noor Real Estate', 
    'realestate', 
    '🏡', 
    '#A855F7', 
    '#7E22CE', 
    '+923249116764', 
    'Hi! 🏡 Welcome to Al-Noor Real Estate. Looking to buy, sell, or rent property in Swat?', 
    'You are an expert AI agent for Al-Noor Real Estate, Swat. FAQs:\n{FAQS_LIST}\nProperties:\n{SERVICES_LIST}. Keep replies brief (max 2 sentences) and capture the customer''s contact info immediately.',
    '[{"q": "What locations do you cover?", "a": "We cover Mingora, Kabal, Kanju, and Madyan properties."}, {"q": "Do you offer installments?", "a": "Yes, we have 2-year installment plans on select housing plots."}]'::jsonb,
    '[{"name": "5-Marla Plot (Kanju)", "price": "PKR 2,500,000"}, {"name": "1-Kanal Plot (Kabal)", "price": "PKR 8,500,000"}]'::jsonb,
    '9 AM - 6 PM', 
    'Kanju, Swat'
  ),
  (
    'restaurant', 
    'Taste of Swat', 
    'restaurant', 
    '🍽️', 
    '#E8471C', 
    '#C2410C', 
    '+923249116764', 
    'Welcome! 🍔 Ready to experience the finest food? I can show our menu or book a table reservation for you.', 
    'You are the friendly AI Host for Taste of Swat Restaurant. FAQs:\n{FAQS_LIST}\nMenu Items:\n{SERVICES_LIST}. Help visitors book a table by asking for name, phone, date, and party size.',
    '[{"q": "Do you deliver?", "a": "Yes, we offer free home delivery within Mingora on orders over PKR 1,000."}, {"q": "Are you family friendly?", "a": "Yes, we have a fully isolated private family seating section."}]'::jsonb,
    '[{"name": "Mutton Karahi (Full)", "price": "PKR 3,200"}, {"name": "Special Chicken Biryani", "price": "PKR 450"}, {"name": "Mint Margarita", "price": "PKR 250"}]'::jsonb,
    '12 PM - 12 AM', 
    'G.T. Road, Mingora, Swat'
  )
ON CONFLICT (id) DO NOTHING;
